server:
    port: 6060


spring:
    application:
        name: Discovery

    datasource:
        url: jdbc:postgresql://localhost:7000/projetSpringBoot
        username: postgres
        password: MohamedTwinTowers1109

    jpa:
        hibernate:
            ddl-auto: create-drop

        show-sql: true

        properties:
            hibernate:
                format-sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect


    web:
        resources:
            static-locations: classpath:/static/
            cache:
                period: 0


